### ISSUE TITLE
quit by "q" key

### ISSUE THREAD

**Issue by tuanth66** [antonmedv/walk#105]
Hi,
thank you for made this program.
I think you can add "q" key as quit like "ESC" is good. Please do it if you think so.
And thank again.
-Tuan

**Comment by antonmedv** [comment]
We already have two methods: ctrl+c and esc.

**Comment by tuanth66** [comment]
of course I can see it. "q" key is easier to remember and press on the keyboard btw.

**Comment by antonmedv** [comment]
Done! Now works with `q` as well.
