### ISSUE TITLE
How to preview image?

### ISSUE THREAD

**Issue by ChangheeOh** [antonmedv/walk#107]
When I retrieving some images as below, I can't preview any of them.
Do I miss some installing plugin or configuring something?

<img width="740" alt="스크린샷 2023-08-27 09 33 34" src="https://github.com/antonmedv/walk/assets/37463335/5f5cb29c-318c-459b-91ff-85dfd318a924">

**Comment by antonmedv** [comment]
> Do I miss some installing plugin or configuring something?

There is no such feature.

**Comment by antonmedv** [comment]
![images-mode](https://github.com/antonmedv/walk/assets/141232/6ae4e6f9-ab4e-4163-a3f7-695066352fac)
Done!
