### ISSUE TITLE
[Usage] For a more concise error log

### ISSUE THREAD

**Issue by hyunsooda** [antonmedv/walk#111]
If an error occurs while executing the `walk` command, it results in the display of verbose panic logs. Comparatively, the default log output of the GNU `ls` command appears to be more succinct than that of the `walk` command. Is it possible to contemplate the adoption of an established convention in the upcoming version?

Concise:
```shell
> ls notexist
"notexist": No such file or directory (os error 2)
```

As-Is:
```shell
> lk notexist
panic: open /home/notexist: no such file or directory

goroutine 1 [running]:
main.(*model).list(0xc0000e6000)
	/home/go/pkg/mod/github.com/antonmedv/walk@v1.5.2/main.go:593 +0x2be
main.main()
	/home/go/pkg/mod/github.com/antonmedv/walk@v1.5.2/main.go:101 +0x27b
```

**Comment by antonmedv** [comment]
Fixed!
