### ISSUE TITLE
command not found: walk

### ISSUE THREAD

**Issue by bilalbayasut** [antonmedv/walk#115]
I have followed the setup in ubuntu using zsh, but got `command not found: walk` any ideas guys ?

**Comment by antonmedv** [comment]
Try `stroll` instead.

**Comment by bilalbayasut** [comment]
not found either

**Comment by antonmedv** [comment]
Hmmmmm. Try: `stumble`.

**Comment by bilalbayasut** [comment]
wow it works! , thanks @antonmedv
