### ISSUE TITLE
Walk rendering issue within tmux on WSL Ubuntu

### ISSUE THREAD

**Issue by jp-mango** [antonmedv/walk#136]
# Description

When running the `walk` command inside Tmux on WSL Ubuntu, the highlight indicating the currently selected file or directory disappears. The navigation functionality still works, but I cannot visually see my current position. This issue does not occur when running `walk` outside of Tmux.

## Steps To Reproduce

1. Open terminal with WSL Ubuntu
2. Run `tmux`
3. Run `lk`

## Expected vs. Actual Behavior

The currently selected file or directory should be highlighted to indicate my position. But, there is no visual highlight to show my current position when navigating with walk inside Tmux.

## Environment

- OS: WSL Ubuntu - Ubuntu 22.04.4 LTS
- `tmux` version - tmux 3.2a
- `walk` version - walk  v1.7.0

## Additional Info

Tried forcing tmux to use 256-colors with the following `.tmux.conf` settings but no dice:

```bash
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
```

![image](https://github.com/antonmedv/walk/assets/23020191/4e745ab1-e1c7-4684-8e16-bab653e61eed)

**Comment by antonmedv** [comment]
Related https://github.com/charmbracelet/bubbletea/issues/825?

**Comment by jp-mango** [comment]
`export COLORTERM=truecolor` worked. Thank You!
