### ISSUE TITLE
Why the searchMode will quit automatically after delay of 2 seconds? I think this is not convenient for users

### ISSUE THREAD

**Issue by rustyhu** [antonmedv/walk#137]
I have used `/` `searchMode` when `walk` my paths and felt confused. I find this logic in the code that when you enter `searchMode`, if you stop typing any runes for 2 seconds then the mode will quit automatically.

I think it is natural for user to think for a while or need to pause sometimes when enter long names then continue to type and search. It seems not convenient.

**Comment by antonmedv** [comment]
This is what I thought would be nice. Just press / and type your dir name. 

What about adding `--fuzzy` flag so search mode is enabled all the time by default?

**Comment by rustyhu** [comment]
It may be nice to have a way to keep in search mode then quit manually, at least for me. As this looks similar to the search mode in general editors.

Just curious, how do you use the search mode that only last for 2 seconds? Just for a very quick searching?

**Comment by antonmedv** [comment]
> Just for a very quick searching?

Yes, I use it not as search, but as quick jump functionality. I know the name of the dir I want to go and qq type the letters to jmp there.

**Comment by shp7724** [comment]
Hi, I also ask the exact same question when I use the search mode.
It would be much more convenient for me to have an option to hold on the search mode. I need more than 2 secs to think of the directory names... 😥

**Comment by antonmedv** [comment]
Actually I know why 2sec is there.

As Backspace is used to "go up", if search more will be always on, we have to figure out how to exit from search mode.

**Comment by antonmedv** [comment]
Hhhmmmmm, I think I know how to improve DX here and drop this 2sec. Let's overload Backspace even more!!! =)))

**Comment by antonmedv** [comment]
Fixed in https://github.com/antonmedv/walk/commit/7366c5501377e2f0e347f6d1fc7fe371b51d140b
