### ISSUE TITLE
Double D to delete is dangerous.

### ISSUE THREAD

**Issue by lvergergsk** [antonmedv/walk#149]
Maybe D -> Y to delete is better.
I loss some important folders as an new walk user.

**Comment by antonmedv** [comment]
Double d is a same key binding as in vim (delete a line). Also walk allows to undo the delete for 5 sec with `u` key.

Alternatively configure walk to move files to trash instead of rm with https://www.npmjs.com/package/trash-cli

```
export WALK_REMOVE_CMD=trash
```

**Comment by lvergergsk** [comment]
OK, sounds reasonable.
I'll try WALK_REMOVE_CMD instead, thanks.
