### ISSUE TITLE
Exit with cd doesn't work

### ISSUE THREAD

**Issue by danisvaliev001** [antonmedv/walk#153]
Exit with cd by pressing esc/q doesn't work in macOS, zsh. Hotkeys behavior almost same as ctrl-c – esc/q prints absolute path of last dir before quit.

**Comment by antonmedv** [comment]
<!DOCTYPE html><head></head><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: var(--base-size-16);">Put the next function into the<span class="Apple-converted-space"> </span><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">.bashrc</strong><span class="Apple-converted-space"> </span>or a similar config:</p>
Bash/Zsh | Fish | PowerShell
-- | -- | --
function lk {   cd "$(walk "$@")" } | function lk   set loc (walk $argv); and cd $loc; end | function lk() {   cd $(walk $args) }

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: var(--base-size-16);">Now use<span class="Apple-converted-space"> </span><code style="box-sizing: border-box; font-family: var(--fontStack-monospace, ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace); font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; white-space: break-spaces; background-color: var(--bgColor-neutral-muted, var(--color-neutral-muted)); border-radius: 6px;">lk</code><span class="Apple-converted-space"> </span>command to start walking.</p><div class="markdown-heading" dir="auto" style="box-sizing: border-box; position: relative;"></h3><br class="Apple-interchange-newline">
