### ISSUE TITLE
Show/hide hidden files

### ISSUE THREAD

**Issue by acn128** [antonmedv/walk#46]
Hi,

would it be possible to add eg. the key binding " . " to toggle the visibility of 'hidden' files and directories (ie. filename start with '.')?

Thank you!

**Comment by antonmedv** [comment]
Sure.

**Comment by amagnolo** [comment]
When was this implemented? The key binding "." doesn't work for me, and it's not in the documentation... any chance it was lost?

**Comment by antonmedv** [comment]
Looks like.

**Comment by amagnolo** [comment]
can you reopen this issue or should I open a new feature request?

**Comment by mjsteinbaugh** [comment]
+1 for adding support for this -- happy to help test

**Comment by matterpale** [comment]
+1, same

**Comment by amagnolo** [comment]
Actually, hiding hidden files should be the default behavior: they are **hidden** for a reason, and _by definition_ showing them in a terminal navigator is a bug.
So the patch should be changed to show hidden files only when explicitly requested by pressing ".".

**Comment by amagnolo** [comment]
I was excited to see v1.8.0 released today... what a disappointment that this lost feature was not restored 😞

**Comment by antonmedv** [comment]
Let's release 1.9)
