### ISSUE TITLE
Is this possible to add some my key bindings? "q" for quit, "r" for rename.

### ISSUE THREAD

**Issue by ProgrammingLife** [antonmedv/walk#51]
I wanna bind "q" for quit for instance?
"yy" would copy dirpath or a filepath into clipboard
"r" for renaming file/dir, why not? 😀 
It would be the greatest tool I've ever seen. But definitely it now already is.

**Comment by antonmedv** [comment]
We can add such key bindings. Question: q exits with cd or not?

**Comment by TheReptar** [comment]
I've noticed at least a couple of issues/PRs concerning key bindings... To avoid bloating the default binding set, would it be beneficial to add some method of configuration?

For example, a .yml, .json, etc file in a known location could work. A lot of tools I use place config files in the ~/.config directory, so something like `~/.config/llama/config.yml` or `~/.config/llama/config.yml`, perhaps? This would open the door to future customizations as well without having to specifically accommodate unique needs directly in the source code.

**Comment by arun-tanksali** [comment]
> We can add such key bindings. Question: q exits with cd or not?

I would request the same key-bindings, particularly 'q' to quit. I would suggest exiting without "cd".  I (and some people I know) use ll mapped to some alias of "ls" and the no-cd will sort of retain that behaviour.

**Comment by Bellavene** [comment]
Customizable key bindings?
Would be much better
