### ISSUE TITLE
snap install on ARM installs wrong binary 

### ISSUE THREAD

**Issue by blackjack75** [antonmedv/walk#52]
I suspect it returns the intel version. If there is no ARM / ARM64 version it should  not be available for ARM devices

**Comment by blackjack75** [comment]
Thanks ! So solution was indeed to make it not available on ARM64 for snap ? I manually downloaded the prebuilt ARM64  binary which works beautifully on RaspberryPi but if I install with snap I still get

sudo snap install walk
error: snap "walk" is not available on stable for this
       architecture (arm64) but exists on other architectures

**Comment by antonmedv** [comment]
I just didn't specify arch in my span.yaml. Don'r know why Ubuntu decided to build only one arch.
