### ISSUE TITLE
ImageMagick is not invoked correctly for .JPG files in home directory

### ISSUE THREAD

**Issue by gregkrsak** [antonmedv/walk#59]
llama (1.0.1-4-g0fad6ce) does not invoke ImageMagick on Lubuntu (21.10) when imagemagick (8:6.9.11.60+dfsg-1ubuntu1) is already installed.

Error received:
~~~
No identify available
Install ImageMagick to browse images
~~~

**Comment by gregkrsak** [comment]
Llama was installed via snap; imagemagick was installed via apt.

**Comment by antonmedv** [comment]
Check you PATH.
