### ISSUE TITLE
Preview mode trims off file content in view

### ISSUE THREAD

**Issue by iddev5** [antonmedv/walk#78]
Best explained by this screenshot. It is the standard license file in a directory called ``~/Projects/llama``

Observed on master, only in preview mode. To replicate just do ``llama .`` and then <SPACE>

Terminal: GNOME Terminal
Go version: 1.20.1

![llama](https://user-images.githubusercontent.com/54106488/223513946-5370234b-5107-4735-be15-81440644adfd.png)

**Comment by antonmedv** [comment]
Llama tries to show as much content as possible in preview mode - trims path.

But why does it trims content in preview - it is strange. 

Please share the file.

**Comment by iddev5** [comment]
It is llama's license file. If you notice carefully not only it is trimming the content but also replacing the top part with something present at the bottom part of the license text.

Also I believed path trimming should have some better strategy, something like shortening it to single letters? ``~/P/l``

**Comment by antonmedv** [comment]
> something like shortening it to single letters? ~/P/l

Will be cool to have. Will you send a pr?)

**Comment by iddev5** [comment]
Some more screenshots of the original issue (Couldn't find why its happening):
![llama-2](https://user-images.githubusercontent.com/54106488/223727216-14f6653a-f283-48ef-9b2d-9e2ddd502cf8.png)
![llama-3](https://user-images.githubusercontent.com/54106488/223727230-b62c78fa-dbe7-4a4c-bace-7f661b684a81.png)

**Comment by antonmedv** [comment]
Fixed.
