### ISSUE TITLE
Command-line argument to start in search mode

### ISSUE THREAD

**Issue by oli-g-sk** [antonmedv/walk#82]
This is a super neat tool, but what bothers me is that I **have to press `/` everytime I use it**. I would be extremely happy if someone could add a command-line argument (`--search` or something) that would make the app switch to search mode automatically after startup.

I practically want search to be active at all times, and I'm sure many others do as well. This extra keystroke cuts the usefulness, speed and productivity in half. The key is pretty far away too (so much hand movement needed) 😄

I realize it's a simple tweak and I could do it myself. Eventually I even might, once I have some time to get myself familiar with Go. But if someone beats me to it, that would be awesome!

**Comment by TheReptar** [comment]
Hey @oli-g-sk, sorry for the delay I didn't see this issue until just now.

Funny enough I had the exact same thought/use-case as you and wanted llama to start in search mode as well as stay in search mode while I was stepping through directories. The fuzzy search kept timing out on me while I was thinking about what I was searching for 😅

I have a fork ([TheReptar/llama](https://github.com/TheReptar/llama)) that actually has that functionality built-in as of about a month ago. I maintain a specific branch for that feature ([TheReptar/llama#allow-instant-search](https://github.com/TheReptar/llama/tree/allow-instant-search)) as I had intended to eventually merge it here once #56 is merged in (the feature is dependent on the configurability that PR adds), but all that functionality is also included in the [master](https://github.com/TheReptar/llama) branch.

You're more than welcome to use my fork if you're interested in that feature set plus some other configurable goodies. It's all enabled/disabled via a configuration file, so please feel free to check out the [Application Behaviors](https://github.com/TheReptar/llama#application-behaviors) and [Configuration Schema](https://github.com/TheReptar/llama#configuration-schema) sections of my fork's README for details on how to get that set up.

Happy hacking! 😁

**Comment by unexist** [comment]
Hey @TheReptar,

I'd love to see that in the official version of walk - why not porting it back and create a PR? :)
